import {useEffect,useMemo,useState} from 'react';
import {logicalInventories,sortedEntries,parseCards,recordYear,statusNames,sourceNoteFields,editorDefaults,editorPayload} from './model.js';
import BulkEdit from './BulkEdit.jsx';
export default function ListingEditor({record,categories,blocked,onSave,onDirty,onRemove}){
 const storedRecord=record;record=useMemo(()=>{const mode=editorDefaults(storedRecord).list_type;return {...storedRecord,list_type:mode,groups:storedRecord.groups.map(g=>({...g,list_type:g.kind==='primary'&&g.list_type==='uncertain'?mode:g.list_type}))};},[storedRecord]);
 const initial=()=>editorDefaults(storedRecord);
 const [form,setForm]=useState(initial),[changes,setChanges]=useState({}),[additions,setAdditions]=useState([]),[input,setInput]=useState(''),[kind,setKind]=useState(record.id.startsWith('display-')?'names':'numbers'),[search,setSearch]=useState(''),[bulk,setBulk]=useState(null),[showAll,setShowAll]=useState(false),[confirm,setConfirm]=useState(false),[confirmedConversion,setConfirmedConversion]=useState(false),[pendingRemove,setPendingRemove]=useState(null),[conversion,setConversion]=useState(false),[error,setError]=useState(''),[destination,setDestination]=useState('');
 const dirty=JSON.stringify(initial())!==JSON.stringify(form)||Object.keys(changes).length>0||additions.length>0||input.trim().length>0;
 useEffect(()=>onDirty(dirty),[dirty]);
 const inventories=useMemo(()=>logicalInventories(record),[record]);
 let draftInventories=inventories.map(g=>({...g,entries:[...g.entries.map(i=>({...i,...changes[i.id],deleted_at:changes[i.id]?.removed?'draft':i.deleted_at})),...additions.filter(a=>a.target===g.id)]}));
 const converting=['want_list','have_list'].includes(form.list_type)&&form.list_type!==record.list_type;
 if(converting&&confirmedConversion)draftInventories=[{id:'conversion',entries:additions,groups:[]}];
 const editable=form.list_type!=='complete';
 const target=destination||inventories[0]?.id||'new-primary';
 const change=k=>e=>{setForm({...form,[k]:e.target.value});if(k==='list_type'){setConfirm(false);setConfirmedConversion(false);if(['want_list','have_list'].includes(e.target.value)&&e.target.value!==record.list_type){setConversion(true);setBulk('conversion');}}};
 function patch(i,extra){if(i.id.startsWith('draft-')){setAdditions(old=>extra.removed?old.filter(a=>a.id!==i.id):old.map(a=>a.id===i.id?{...a,...extra}:a));return;}setChanges(old=>{const next={...old,[i.id]:{id:i.id,state:i.state,removed:false,...old[i.id],...extra}},source=record.groups.flatMap(g=>g.entries).find(x=>x.id===i.id);if(!next[i.id].removed&&next[i.id].state===source.state)delete next[i.id];return next;});}
 function add(values,field,targetId=target){const active=draftInventories.flatMap(g=>g.entries.filter(i=>!i.deleted_at&&!i.removed));if(values.some(v=>active.some(i=>i.value===v)))throw Error('An entry is already in this list.');setAdditions(old=>[...old,...values.map(value=>({id:'draft-'+crypto.randomUUID(),target:targetId,group_id:converting?'new-primary':targetId,value,field_key:field,state:form.list_type==='have_list'?'owned':'wanted',actionable:1,position:old.length}))]);}
 function applyBulk(extra,g){
  const active=g.entries.filter(i=>!i.deleted_at),same=!conversion;
  const keep=new Set(extra.values);const next={...changes};
  for(const i of active.filter(i=>!i.id.startsWith('draft-')))if(!same||!keep.has(i.value))next[i.id]={id:i.id,state:i.state,removed:true};
  setChanges(next);const remaining=additions.filter(a=>a.target!==g.id||(same&&keep.has(a.value)));
  const fresh=extra.values.filter(v=>!same||!active.some(i=>i.value===v));
  setAdditions([...remaining,...fresh.map(value=>({id:'draft-'+crypto.randomUUID(),target:g.id,group_id:conversion?'new-primary':g.id,value,field_key:extra.field_key,state:form.list_type==='have_list'?'owned':'wanted',actionable:1}))]);
  if(conversion)setConfirmedConversion(true);setBulk(null);setConversion(false);
 }
 async function save(){setError('');try{
  if(input.trim()){setError('Add the entered cards/items to the draft before saving.');return;}
  if(converting&&!confirmedConversion)throw Error('Confirm the new represented identifiers with Bulk Edit.');
  await onSave({...editorPayload(storedRecord,form),changes:Object.values(changes),additions:additions.map(({value,field_key,group_id,state})=>({value,field_key,group_id,state})),confirm_complete:confirm,confirm_conversion:confirmedConversion,confirm_pending_removal:true});
 }catch(e){setError(e.message);}}
 const all= draftInventories.flatMap(g=>g.entries.filter(i=>!i.deleted_at&&!i.removed));
 const newInventory=converting?{id:'conversion',entries:all,groups:inventories.flatMap(g=>g.groups)}:null;
 return <div className="listing-editor"><div className="save-bar"><button className="primary-button" disabled={blocked||!dirty||Object.keys(changes).length>500||additions.length>500||(form.list_type==='complete'&&form.list_type!==record.list_type&&!confirm)||converting&&!confirmedConversion} onClick={save}>{blocked?'Saving…':'Save changes'}</button><span role="status">{dirty?'Unsaved changes':'No changes to save'}</span></div>
 {error&&<p role="alert">{error}</p>}
 {Object.keys(changes).length>500||additions.length>500?<p role="alert">Save supports up to 500 changed entries and 500 additions. Reduce this draft before saving.</p>:null}
 <fieldset disabled={blocked}><div className="form-grid"><label>Year or years<input value={form.year} onChange={change('year')}/></label><label>Manufacturer<input value={form.brand} onChange={change('brand')}/></label><label className="wide">Set name<input required maxLength={500} value={form.set_name} onChange={change('set_name')}/></label><label>Category<select value={form.display_category} onChange={change('display_category')}>{!form.display_category&&<option value="">Choose a category</option>}{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>List type<select value={form.list_type} onChange={change('list_type')}>{!['want_list','have_list','complete'].includes(form.list_type)&&<option value={form.list_type}>Original source wording</option>}{['want_list','have_list','complete'].map(m=><option key={m} value={m}>{statusNames[m]}</option>)}</select></label><label className="wide">Notes<textarea rows={4} value={form.notes} onChange={change('notes')}/></label></div>
 {form.list_type==='complete'&&form.list_type!==record.list_type&&<label className="check"><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/>I confirm this set is COMPLETE. Prior entries remain recoverable.</label>}
 <label>Entry order<select value={form.entry_order} onChange={change('entry_order')}><option value="natural">Natural order</option><option value="original">Original order</option></select></label>
 <form onSubmit={e=>{e.preventDefault();try{add(parseCards(input,kind),kind==='names'?'items':'card_numbers');setInput('');setError('');}catch(e){setError(e.message);}}}><h3>Add cards/items</h3>{inventories.length>1&&<label>Inventory<select value={target} onChange={e=>setDestination(e.target.value)}>{inventories.map((g,i)=><option key={g.id} value={g.id}>{g.label||'Primary list '+(i+1)}</option>)}</select></label>}<label>Entry format<select value={kind} onChange={e=>setKind(e.target.value)}><option value="numbers">Numbers or codes</option><option value="names">Names, one per line</option></select></label><label>{kind==='names'?'One name or item on each line':'Card numbers or codes'}<textarea value={input} onChange={e=>setInput(e.target.value)} rows={3}/></label><p>Names stay one per line, including commas. Literal ranges are not expanded.</p><button disabled={!input.trim()||!editable||converting&&!confirmedConversion}>Add to draft</button>{!editable&&<p>Change List type before adding entries.</p>}</form>
 <label>Search within listing<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label>
 {bulk==='conversion'&&<BulkEdit key={'conversion'+form.list_type} group={{...newInventory,list_type:record.list_type}} conversion={form.list_type} record={record} blocked={blocked} onApply={extra=>applyBulk(extra,newInventory)} onCancel={()=>{setForm({...form,list_type:record.list_type});setBulk(null);setConversion(false);}}/>}
 {(draftInventories.length?draftInventories:[{id:'new-primary',entries:additions,groups:[]}]).map(g=><section key={g.id} className="owner-group"><h3>{g.label||'Current cards/items'}</h3>{g.description&&<p>{g.description}</p>}{(g.notes||[]).filter(n=>!(record.content.notes||[]).includes(n)).map((n,i)=><p key={'note'+i}>{n}</p>)}{!converting&&editable&&<button onClick={()=>{setBulk(g.id);setConversion(false);}}>Bulk Edit</button>}{bulk===g.id&&<BulkEdit key={g.id} group={{...g,list_type:form.list_type}} record={record} blocked={blocked} onApply={extra=>applyBulk(extra,g)} onCancel={()=>setBulk(null)}/>}
 {['active','pending'].map(section=>{const items=sortedEntries(g.entries.filter(i=>!i.deleted_at&&!i.removed&&(section==='pending'?i.state==='pending':i.state!=='pending'&&(record.list_type!=='want_list'||i.state!=='owned'))&&i.value.toLowerCase().includes(search.toLowerCase())),form.entry_order==='original');return items.length>0&&<div key={section}>{section==='pending'&&<h4>Pending</h4>}{items.slice(0,showAll?undefined:40).map(i=><div className="owner-item" key={i.id}><strong>{i.value}</strong><div className="item-actions">{editable&&!converting&&form.list_type==='want_list'&&section==='active'&&<button onClick={()=>patch(i,{state:'pending'})}>Mark Pending</button>}{editable&&!converting&&section==='pending'&&<button onClick={()=>patch(i,{state:'wanted'})}>Cancel Pending</button>}<button disabled={!editable||converting} onClick={()=>i.state==='pending'?setPendingRemove(i):patch(i,{removed:true})}>Remove</button></div></div>)}{items.length>40&&!showAll&&<button onClick={()=>setShowAll(true)}>Show all entries</button>}</div>;})}</section>)}
 {pendingRemove&&<section className="remove-confirm"><p>Remove pending entry {pendingRemove.value}?</p><button onClick={()=>{patch(pendingRemove,{removed:true});setPendingRemove(null);}}>Confirm removal</button><button onClick={()=>setPendingRemove(null)}>Keep entry</button></section>}
 {record.content.uncertainty?.map((n,i)=><p key={i}>{n}</p>)}
 {record.groups.filter(g=>g.kind==='primary'&&sourceNoteFields(record.id).length||g.list_type!==record.list_type||record.list_type==='want_list'&&g.entries.some(i=>!i.deleted_at&&i.state==='owned')).map(g=><details key={g.id}><summary>Historical notes{g.label?': '+g.label:''}</summary>{g.description&&<p>{g.description}</p>}<p>{g.entries.filter(i=>!i.deleted_at&&(g.list_type!==record.list_type||i.state==='owned'||g.kind==='primary'&&sourceNoteFields(record.id).includes(i.field_key))).map(i=>i.value).join('; ')}</p>{g.notes?.map((n,i)=><p key={i}>{n}</p>)}</details>)}
 <button className="remove-set" onClick={onRemove}>Remove set</button>
 </fieldset></div>;
}
