import {it,expect} from 'vitest';import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import Browse from '../../owner/Browse.jsx';import {browseRecord,logicalInventories} from '../../owner/model.js';import view from '../../foundation/staging/historical-view.json';
it('ownership prose remains a note, never a needed identifier or an editable primary inventory',async()=>{
 const source=view.records.find(r=>r.id==='p0526-l006');const live={id:source.id,set_name:source.set_name,display_category:'Other Stuff',list_type:'want_list',groups:[{id:'g',kind:'primary',list_type:'want_list',entries:source.items.map((value,n)=>({id:'i'+n,value,field_key:'items',actionable:0,state:null}))}]};
 expect(logicalInventories(live).flatMap(g=>g.entries)).toHaveLength(0);const mapped=browseRecord(live);expect(mapped.supplemental_notes.join(' ')).toContain('I have all of the Topps');const {container}=render(<Browse records={[mapped]}/>);fireEvent.change(screen.getByLabelText('Category'),{target:{value:'Other Stuff'}});fireEvent.click(container.querySelector('summary'));await waitFor(()=>expect(container.querySelector('.listing-content')).not.toBeNull());expect(container.querySelector('.listing-content').textContent).toContain('I have all of the Topps');expect(container.querySelector('.listing-content').textContent).not.toContain('Cards I NEED:');expect(container.querySelector('.listing-content').textContent).not.toContain('Preserved Source Information');
});
it('Pending is searchable, rendered once, and absent from ordinary needed entries; previous ownership stays private',async()=>{
 const mapped=browseRecord({id:'r',set_name:'Test',display_category:'OBC Wantlist',list_type:'want_list',groups:[{id:'g',kind:'primary',list_type:'want_list',entries:[{id:'1',value:'1',state:'wanted',actionable:1},{id:'2',value:'47',state:'pending',actionable:1},{id:'3',value:'15',state:'owned',actionable:1}]}]});
 const {container}=render(<Browse records={[mapped]}/>);fireEvent.change(screen.getByLabelText('Search this category'),{target:{value:'47'}});expect(container.querySelectorAll('.listing-row')).toHaveLength(1);fireEvent.click(container.querySelector('summary'));await waitFor(()=>expect(container.querySelector('.listing-content')).not.toBeNull());const content=container.querySelector('.listing-content').textContent;expect(content).toContain('Pending: 47');expect(content.match(/47/g)).toHaveLength(1);expect(content).not.toContain('Historical owned information');expect(content).not.toContain('15');expect(content).not.toContain('Cards I HAVE:');
});
