import {it,expect,afterEach} from 'vitest';import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react';
import {readFileSync} from 'node:fs';import Browse,{CATEGORIES} from '../../owner/Browse.jsx';import {browseRecord} from '../../owner/model.js';
afterEach(cleanup);
const example={id:'owner-record-example',set_name:'2028 Bowman Chrome Test',year:'2028',brand:'Bowman',display_category:'UV Wantlist',list_type:'want_list',notes:['just collecting the first 10 cards'],groups:[{id:'owner-group-test',kind:'primary',list_type:'want_list',entries:['2','4','6','8','10'].map((value,n)=>({id:'legacy-'+n,value,state:n===0?'owned':'wanted',actionable:1}))}]};
async function expand(r){const result=render(<Browse records={[r]}/>);if(r.display_category!=='OBC Wantlist')fireEvent.change(screen.getByLabelText('Category'),{target:{value:r.display_category}});fireEvent.click(result.container.querySelector('summary'));await waitFor(()=>expect(result.container.querySelector('.listing-content')).not.toBeNull());return result.container.querySelector('.listing-content');}
it('Bowman example hides ownership remnants, preserves wanted identifiers, notes and input data',async()=>{const before=JSON.stringify(example),mapped=browseRecord(example),content=await expand(mapped);expect(content).toHaveTextContent('Cards I NEED: 4, 6, 8, 10');expect(content).toHaveTextContent('just collecting the first 10 cards');expect(mapped.supplemental_notes).toEqual([]);expect(content).not.toHaveTextContent(/Historical|Owned:|Cards I HAVE|information/);expect(JSON.stringify(example)).toBe(before);});
it('WANT pending and HAVE owned inventories use exact capitalized labels without secondary inventories',async()=>{for(const mode of ['want_list','have_list']){const r={...example,id:'owner-record-'+mode,display_category:'OBC Wantlist',list_type:mode,groups:[{id:'owner-group-primary',kind:'primary',list_type:mode,entries:[{id:'1',value:'1',state:mode==='want_list'?'wanted':'owned'},{id:'2',value:'47',state:mode==='want_list'?'pending':'owned'}]},{id:'owner-group-old',kind:'mixed',list_type:mode==='want_list'?'have_list':'want_list',entries:[{id:'old',value:'OLD-RECOVERY',state:'owned'}]}]};const content=await expand(browseRecord(r));expect(content).toHaveTextContent(mode==='want_list'?'Cards I NEED: 1':'Cards I HAVE: 1, 47');expect(content).not.toHaveTextContent('OLD-RECOVERY');if(mode==='want_list'){expect(content).toHaveTextContent('Pending: 47');expect(content.textContent.match(/47/g)).toHaveLength(1);}cleanup();}});
it('important original opposite inventory remains a plain note while later received/added values remain private',async()=>{const g='p1566-l003:mixed:0',r={id:'p1566-l003',set_name:'Variants',display_category:'UV Wantlist',list_type:'want_list',notes:[],groups:[{id:g,kind:'mixed',list_type:'have_list',label:'Blue variant',description:'Keep this qualification.',entries:[{id:g+':items:0',value:'Original owned variant',state:null},{id:'owner-item-new',value:'Later owner addition',state:'owned'},{id:g+':items:1',value:'Received remnant',state:'owned',received_at:'2026-10-09'}]}]};const content=await expand(browseRecord(r));expect(content).toHaveTextContent('Blue variant: Owned: Original owned variant');expect(content).toHaveTextContent('Keep this qualification.');expect(content).not.toHaveTextContent(/Later owner addition|Received remnant|Historical/);expect(content.querySelectorAll('section')).toHaveLength(0);});
it('all seven categories retain listings, special collections use Items I HAVE/NEED and original source prose survives',async()=>{for(const category of CATEGORIES){const mode=category==='Milwaukee 8x10 List'?'have_list':'want_list',special=['Milwaukee 8x10 List','Eau Claire Players','Brewers Bobblehead Wantlist'].includes(category),r={...example,id:category==='Eau Claire Players'?'display-eau-claire-1':category==='Milwaukee 8x10 List'?'display-milwaukee-8x10-list':'owner-record-test',display_category:category,list_type:mode,groups:[{id:'g',kind:'primary',list_type:mode,entries:[{id:'i',value:'Example identifier',state:mode==='have_list'?'owned':'wanted'}]}]};const content=await expand(browseRecord(r));expect(content).toHaveTextContent(`${special?'Items':'Cards'} I ${mode==='have_list'?'HAVE':'NEED'}: Example identifier`);cleanup();}const view=JSON.parse(readFileSync('foundation/staging/historical-view.json')).records,r=view.find(r=>r.id==='p0526-l006');const content=await expand(r);expect(content).toHaveTextContent('I have all of the Topps');expect(content).not.toHaveTextContent(/Historical|Preserved Source Information|Original wording/);});
it('raw derived source records retain effective HAVE primary inventories and ordinary source notes',async()=>{const view=JSON.parse(readFileSync('foundation/staging/historical-view.json')).records;const r=view.find(r=>r.id==='p0023-l001');const content=await expand(r);expect(content).toHaveTextContent('Cards I HAVE:');expect(content.textContent).toContain(r.card_numbers[0]);});

it('HAVE primary inventory does not present old wanted or pending states as owned',async()=>{const r={...example,list_type:'have_list',display_category:'OBC Wantlist',groups:[{id:'owner-group-have',kind:'primary',list_type:'have_list',entries:[{id:'a',value:'1',state:'owned'},{id:'b',value:'OLD-WANTED',state:'wanted'},{id:'c',value:'OLD-PENDING',state:'pending'}]}]};const content=await expand(browseRecord(r));expect(content).toHaveTextContent('Cards I HAVE: 1');expect(content).not.toHaveTextContent(/OLD-WANTED|OLD-PENDING|Pending:/);});
