import {it,expect,afterEach,vi} from 'vitest';import {render,screen,fireEvent,cleanup,waitFor} from '@testing-library/react';import {readFileSync} from 'node:fs';
import Browse,{CATEGORIES,compactStatus} from '../../owner/Browse.jsx';import ListingEditor from '../../owner/ListingEditor.jsx';import {browseRecord,editorDefaults,currentNotesText,publicSourceNotes} from '../../owner/model.js';
afterEach(cleanup);
const view=JSON.parse(readFileSync('foundation/staging/historical-view.json')).records;
const source=view.find(r=>r.id==='p1566-l003');
const live={...source,groups:[{id:'p1566-l003:primary:0',kind:'primary',list_type:'want_list',notes:['PRIMARY-ARCHIVE-SENTINEL'],description:'PRIMARY-DESCRIPTION-SENTINEL',entries:[{id:'blue',field_key:'items',value:'Blue Border Griffey',state:'wanted',actionable:1}]},{id:'p1566-l003:mixed:0',kind:'mixed',list_type:'have_list',description:'User-confirmed owned variant.',entries:[{id:'p1566-l003:mixed:0:items:0',field_key:'items',value:'Red Border Griffey',state:'owned'}]}],uncertainty:['UNCERTAINTY-ARCHIVE-SENTINEL'],supplemental_notes:['SUPPLEMENT-ARCHIVE-SENTINEL'],payload:'PAYLOAD-ARCHIVE-SENTINEL',normalized_wording:'NORMALIZED-ARCHIVE-SENTINEL'};
async function expand(r){const result=render(<Browse records={[r]}/>);const category=r.display_category||'UV Wantlist';fireEvent.change(screen.getByLabelText('Category'),{target:{value:category}});fireEvent.click(result.container.querySelector('.listing-row summary'));await waitFor(()=>expect(result.container.querySelector('.listing-content')).not.toBeNull());return result;}
it('live and derived Ritz/Oreo paths show current note once and preserve source/owned evidence internally',async()=>{for(const r of [browseRecord(live),source]){const before=JSON.stringify(r),{container}=await expand(r),content=container.querySelector('.listing-content');expect(content).toHaveTextContent('Cards I NEED: Blue Border Griffey');expect(content.querySelector('.owner-notes').textContent).toBe('Red Border Griffey already owned');expect(content.textContent.match(/Red Border Griffey/g)).toHaveLength(1);expect(content).not.toHaveTextContent(/User-confirmed owned variant|Owned:|ARCHIVE-SENTINEL|DESCRIPTION-SENTINEL/);expect(JSON.stringify(r)).toBe(before);cleanup();}expect(publicSourceNotes(live).join(' ')).toContain('User-confirmed owned variant.');expect(live.groups[1].entries[0].value).toBe('Red Border Griffey');});
it('one editor Notes field, no historical sections, group descriptions or uncertainty, and notes-only save payload',async()=>{const record={id:live.id,list_type:live.list_type,content:live,groups:live.groups},save=vi.fn(),before=JSON.stringify(record),{container}=render(<ListingEditor record={record} categories={CATEGORIES} onDirty={()=>{}} onSave={save} onRemove={()=>{}}/>);expect(screen.getAllByRole('textbox',{name:'Notes',exact:true})).toHaveLength(1);expect(screen.getByRole('textbox',{name:'Notes',exact:true})).toHaveValue(editorDefaults(record).notes);expect(container.textContent).not.toMatch(/Historical notes|User-confirmed owned variant|ARCHIVE-SENTINEL|DESCRIPTION-SENTINEL/);fireEvent.change(screen.getByRole('textbox',{name:'Notes',exact:true}),{target:{value:'Owner selected replacement'}});fireEvent.click(screen.getByRole('button',{name:'Save changes'}));await waitFor(()=>expect(save).toHaveBeenCalled());expect(save.mock.calls[0][0].metadata).toEqual({notes:['Owner selected replacement']});expect(save.mock.calls[0][0]).not.toHaveProperty('list_type');expect(JSON.stringify(record)).toBe(before);});
it('only current Notes render for all categories, owner categories, COMPLETE and unresolved records, with no source fallback',async()=>{for(const category of [...CATEGORIES,'Owner category'])for(const mode of ['want_list','have_list','complete','uncertain']){const r={...browseRecord(live),id:'owner-record-check',display_category:category,list_type:mode,notes:['Current note','  Exact second line  '],uncertainty:['UNCERTAINTY-ARCHIVE-SENTINEL'],supplemental_notes:['SUPPLEMENT-ARCHIVE-SENTINEL'],payload:'PAYLOAD-ARCHIVE-SENTINEL',normalized_wording:'NORMALIZED-ARCHIVE-SENTINEL'};const {container}=render(<Browse records={[r]} categories={[...CATEGORIES,'Owner category']}/>);fireEvent.change(screen.getByLabelText('Category'),{target:{value:category}});fireEvent.click(container.querySelector('summary'));await waitFor(()=>expect(container.querySelector('.listing-content')).not.toBeNull());expect(container.querySelector('.owner-notes').textContent).toBe(currentNotesText(r));expect(container.querySelector('.listing-content').textContent).not.toMatch(/ARCHIVE-SENTINEL|DESCRIPTION-SENTINEL/);cleanup();}});
it('empty current Notes produce no note or archived fallback, and archived text is excluded from ordinary search',async()=>{const r={...browseRecord(live),notes:[]};const {container}=await expand(r);expect(container.querySelector('.owner-notes')).toBeNull();expect(container.querySelector('.listing-content')).not.toHaveTextContent('Red Border Griffey');for(const value of ['UNCERTAINTY-ARCHIVE-SENTINEL','PAYLOAD-ARCHIVE-SENTINEL','NORMALIZED-ARCHIVE-SENTINEL','PRIMARY-ARCHIVE-SENTINEL']){fireEvent.change(screen.getByLabelText('Search this category'),{target:{value}});expect(container.querySelectorAll('.listing-row')).toHaveLength(0);}});
it('all 3394 source classifications, current Notes and inputs remain unchanged by public adaptation',()=>{expect(view).toHaveLength(3394);const before=JSON.stringify(view);for(const r of view){const groups=[{...r,id:r.id+':primary:0',kind:'primary',entries:[...(r.card_numbers||[]).map(value=>({value,field_key:'card_numbers'})),...(r.items||[]).map(value=>({value,field_key:'items'})),...(r.card_ranges||[]).map(value=>({value,field_key:'card_ranges'}))]},...(r.mixed_lists||[]).map((g,i)=>({...g,id:r.id+':mixed:'+i,kind:'mixed',entries:(g.items||[]).map(value=>({value}))})),...(r.sublists||[]).map((g,i)=>({...g,id:r.id+':sublist:'+i,kind:'sublist',entries:(g.items||[]).map(value=>({value}))}))],mapped=browseRecord({...r,groups});expect(compactStatus(mapped),r.id).toBe(compactStatus(r));expect(mapped.notes,r.id).toEqual(r.notes);expect(mapped.supplemental_notes,r.id).toEqual([]);}expect(JSON.stringify(view)).toBe(before);});
