import {test,expect} from '@playwright/test';
import {resolve} from 'node:path';
import {readFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
test('owner-local backup setup offers separate encrypted recovery and public key downloads without network access',async({page})=>{
 const remote=[];page.on('request',r=>{if(/^https?:/.test(r.url())&&r.url()!=='https://isolated.wantlist.test/backup-setup')remote.push(r.url());});await page.route('https://isolated.wantlist.test/backup-setup',route=>route.fulfill({contentType:'text/html',body:readFileSync(resolve('tools/backup-recovery.html'),'utf8')}));await page.goto('https://isolated.wantlist.test/backup-setup');
 await page.getByLabel('Recovery password',{exact:true}).first().fill('ephemeral-test-only-password-123');await page.getByLabel('Repeat recovery password').fill('ephemeral-test-only-password-123');await page.getByRole('button',{name:'Generate recovery files'}).click();
 const publicButton=page.getByRole('button',{name:'Download wantlist-public-key.json',exact:true});await expect(publicButton).toBeVisible({timeout:30000});const ready=page.waitForEvent('download');await publicButton.click();const publicDownload=await ready;expect(publicDownload.suggestedFilename()).toBe('wantlist-public-key.json');
 const privateReady=page.waitForEvent('download');await page.getByRole('button',{name:'Download wantlist-private-recovery-key.ENCRYPTED.json',exact:true}).click();const privateDownload=await privateReady;expect(privateDownload.suggestedFilename()).toContain('ENCRYPTED');// Artificial data and ephemeral test keys only; no owner database or key access.
 const encrypted=execFileSync('python',['-c',"import sys,json;from foundation.staging.encrypted_backup import encrypt;print(json.dumps(encrypt(b'{\"isolated_backup_roundtrip\":true}',json.load(sys.stdin))))"],{input:readFileSync(await publicDownload.path())});
 await page.getByLabel('Password-protected recovery key').setInputFiles({name:'test-key.ENCRYPTED.json',mimeType:'application/json',buffer:readFileSync(await privateDownload.path())});await page.getByLabel('Encrypted database backup').setInputFiles({name:'test-backup.json',mimeType:'application/json',buffer:encrypted});await page.getByLabel('Recovery password',{exact:true}).last().fill('ephemeral-test-only-password-123');await page.locator('#private').check();
 const recoveredReady=page.waitForEvent('download');await page.getByRole('button',{name:'Verify and recover backup'}).click();const recovered=await recoveredReady;expect(JSON.parse(readFileSync(await recovered.path(),'utf8'))).toEqual({isolated_backup_roundtrip:true});
 const tampered=JSON.parse(encrypted);tampered.metadata.plaintext_sha256='tampered';await page.getByLabel('Encrypted database backup').setInputFiles({name:'test-tampered.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(tampered))});await page.getByLabel('Recovery password',{exact:true}).last().fill('ephemeral-test-only-password-123');await page.getByRole('button',{name:'Verify and recover backup'}).click();await expect(page.getByRole('status')).toContainText('Recovery failed');
 expect(remote).toEqual([]);await expect(page.getByLabel('Repeat recovery password')).toHaveValue('');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
