import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
const origin='https://isolated.wantlist.test';
test.beforeEach(async({page})=>{
 await fetch('http://127.0.0.1:5181/reset',{method:'POST'});
 await page.route(origin+'/**',async route=>{const req=route.request();const r=await(await fetch('http://127.0.0.1:5181/relay',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:new URL(req.url()).pathname+new URL(req.url()).search,method:req.method(),headers:await req.allHeaders(),body:req.postData()})})).json();await route.fulfill({status:r.status,headers:r.headers,body:Buffer.from(r.body,'base64')});});
 await page.goto(origin);await expect(page.locator('.listing-row').first()).toBeVisible();
});
test('full collection categories, searchable filters, source years, current notes and responsive public browsing',async({page},info)=>{
 const category=page.getByRole('combobox',{name:'Category',exact:true});
 for(const [name,count] of [['OBC Wantlist',583],['UV Wantlist',2517],['Eau Claire Players',3],['Milwaukee 8x10 List',1],['Brewers Bobblehead Wantlist',26],['Football Wantlist',62],['Other Stuff',202]]){
  await category.selectOption(name);await expect(page.locator('.listing-row')).toHaveCount(count);await page.locator('.listing-row summary').first().click();await expect(page.locator('.listing-content')).toBeVisible();await expect(page.getByRole('button',{name:'Edit this set'})).toHaveCount(0);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 }
 await category.selectOption('UV Wantlist');const year=page.getByRole('combobox',{name:'Year',exact:true});await year.click();await year.fill('1995');await year.press('Enter');
 const manufacturer=page.getByRole('combobox',{name:'Manufacturer',exact:true});await manufacturer.click();await manufacturer.fill('Topps');await page.getByRole('option',{name:'Topps',exact:true}).click();expect(await page.locator('.listing-row').count()).toBeGreaterThan(0);
 await page.screenshot({path:`work/phase3c1-${info.project.name}-filters.png`});
 await page.reload();await category.selectOption('UV Wantlist');await page.getByLabel('Search this category').fill('Ritz/Oreo');await expect(page.locator('.listing-row')).toHaveCount(1);await page.locator('.listing-row summary').click();await expect(page.locator('.listing-content')).toContainText('Blue Border Griffey');await expect(page.locator('.owner-notes')).toHaveText('Red Border Griffey already owned');await expect(page.locator('.listing-content')).not.toContainText('User-confirmed owned variant');
 expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);
});
test('full-scale photo editor adds into historical inventory, saves order and notes, pending works for Eau Claire',async({page},info)=>{
 await page.getByRole('button',{name:'Owner Login',exact:true}).click();await page.getByLabel('Owner PIN',{exact:true}).fill('4826');await page.getByRole('dialog').getByRole('button',{name:'Sign in',exact:true}).click();
 const category=page.getByRole('combobox',{name:'Category',exact:true});await category.selectOption('Milwaukee 8x10 List');await page.locator('.listing-row summary').click();await page.getByRole('button',{name:'Edit this set'}).click();const dialog=page.getByRole('dialog');
 await expect(dialog.locator('.owner-item')).toHaveCount(40);await dialog.getByRole('button',{name:'Show all entries',exact:true}).click();await expect(dialog.locator('.owner-item')).toHaveCount(250);await dialog.getByRole('combobox',{name:'Entry format',exact:true}).selectOption('names');await dialog.getByLabel('One name or item on each line').fill('Isolated, New Name');await dialog.getByRole('button',{name:'Add to draft'}).click();await dialog.getByRole('combobox',{name:'Entry order',exact:true}).selectOption('original');await dialog.getByRole('textbox',{name:'Notes',exact:true}).fill('Current rehearsal note');await dialog.getByRole('button',{name:'Save changes',exact:true}).click();await expect(dialog.getByText('Changes saved',{exact:true})).toBeVisible();
 await dialog.getByRole('button',{name:'Close',exact:true}).click();await expect(page.locator('.listing-content')).toContainText('Isolated, New Name');await expect(page.locator('.listing-content section')).toHaveCount(1);await page.reload();await category.selectOption('Milwaukee 8x10 List');await page.locator('.listing-row summary').click();await expect(page.locator('.owner-notes')).toHaveText('Current rehearsal note');
 await category.selectOption('Eau Claire Players');await page.locator('.listing-row summary').filter({hasText:'Major League Players'}).click();await page.getByRole('button',{name:'Edit this set'}).click();const first=dialog.locator('.owner-item').first();const value=await first.locator('strong').textContent();await first.getByRole('button',{name:'Mark Pending'}).click();await dialog.getByRole('button',{name:'Save changes',exact:true}).click();await expect(dialog.getByText('Changes saved',{exact:true})).toBeVisible();
 expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);expect(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);await page.screenshot({path:`work/phase3c1-${info.project.name}-editor.png`});await dialog.getByRole('button',{name:'Close',exact:true}).click();await expect(page.locator('.listing-content')).toContainText('Pending: '+value);
});
test('largest historical inventory stays complete, bounded editing and bulk limits are explicit',async({page})=>{
 const category=page.getByRole('combobox',{name:'Category',exact:true});await category.selectOption('UV Wantlist');await page.getByLabel('Search this category').fill('2007 Upper Deck');await page.locator('.listing-row summary').filter({has:page.getByText('2007 Upper Deck',{exact:true})}).click();await expect(page.locator('.listing-content')).toContainText('Cards I NEED:');
 await page.getByRole('button',{name:'Owner Login',exact:true}).click();await page.getByLabel('Owner PIN',{exact:true}).fill('4826');await page.getByRole('dialog').getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('button',{name:'Edit this set'}).click();const dialog=page.getByRole('dialog');await expect(dialog.locator('.owner-item')).toHaveCount(40);await dialog.getByRole('button',{name:'Show all entries',exact:true}).click();await expect(dialog.locator('.owner-item')).toHaveCount(526);
 await dialog.getByRole('button',{name:'Bulk Edit',exact:true}).click();expect((await dialog.getByLabel('Current cards/items').inputValue()).split(/\s+/)).toHaveLength(526);await expect(dialog.getByText('Bulk Edit supports up to 500 entries; larger lists are never truncated.')).toBeVisible();await expect(dialog.getByRole('button',{name:'Apply changes',exact:true})).toBeDisabled();await dialog.getByRole('button',{name:'Cancel',exact:true}).click();
 await dialog.getByRole('textbox',{name:'Notes',exact:true}).fill('Largest-list current note');await dialog.getByRole('button',{name:'Save changes',exact:true}).click();await expect(dialog.getByText('Changes saved',{exact:true})).toBeVisible();await dialog.getByRole('button',{name:'Close',exact:true}).click();await expect(page.locator('.owner-notes')).toHaveText('Largest-list current note');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
