import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {localD1} from './d1-local-adapter.mjs';import {maintainPhase35,rollbackEauSplit} from '../staging/phase35-maintenance.js';import {cleanup,eau} from '../staging/phase35-maintenance-data.js';import {mutate,openRecord,publicProjection} from '../staging/records.js';import {recentOwner} from '../staging/owner.js';
function fixture(){const db=localD1();db.sqlite.exec(readFileSync(new URL('../staging/schema.sql',import.meta.url),'utf8'));db.sqlite.exec("INSERT INTO staging_import_state VALUES(1,'test','test',0,1)");const stamp='2026-10-01T00:00:00Z';
 const record=(id,revision,metadata)=>{db.sqlite.prepare('INSERT INTO records VALUES(?,NULL,?,?,?, ?,?,NULL)').run(id,'want_list',JSON.stringify({id,notes:['Keep owner note'],display_category:'Eau Claire Players',...metadata}),revision,stamp,stamp);db.sqlite.prepare('INSERT INTO public_records VALUES(?,?,?,?,?)').run(id,revision,stamp,0,JSON.stringify({id,list_type:'want_list',revision,...metadata,groups:[]}));};
 record(cleanup.record_id,cleanup.revision,{year:'2027',brand:'Topps',notes:cleanup.expected_notes});const gid='benchmark-primary';db.sqlite.prepare('INSERT INTO record_groups VALUES(?,?,?,0,?,?,?)').run(gid,cleanup.record_id,'primary','want_list','{}','["card_numbers"]');
 const ins=db.sqlite.prepare('INSERT INTO items VALUES(?,?,?,?,?,?,?,?,?,?,?)');for(const [n,id] of cleanup.ids.entries())ins.run(id,gid,'card_numbers',n,'cpu-test-local-'+n,'wanted',1,null,null,null,null);ins.run('legitimate',gid,'card_numbers',1403,'1','pending',1,null,stamp,null,null);
 record(eau.parent,eau.revision,{set_name:'Eau Claire Players'});for(const [n,r] of eau.listings.entries()){const g='eau-group-'+n;db.sqlite.prepare('INSERT INTO record_groups VALUES(?,?,?, ?,?,?,?)').run(g,eau.parent,'sublist',n,'want_list',JSON.stringify({label:r.content.set_name}),'["items"]');for(const [pos,value] of r.source.items.entries())ins.run(g+':'+pos,g,'items',pos,value,null,0,'Original broad interest',null,null,null);}
 return db;}
test('confirmed cleanup soft-removes only exact IDs, preserves legitimate Pending/notes, is idempotent and fully Undoable',async()=>{const db=fixture();try{
 const result=await maintainPhase35(db,'cleanup');assert.equal(result.soft_removed,1403);assert.equal((await maintainPhase35(db,'cleanup')).replayed,true);
 let r=await openRecord(db,cleanup.record_id);assert.equal(r.content.year,'2007');assert.equal(r.content.brand,'Upper Deck');assert.deepEqual(r.content.notes,cleanup.metadata.notes);assert.deepEqual(r.groups[0].entries.filter(i=>!i.deleted_at).map(i=>[i.id,i.state]),[['legitimate','pending']]);
 const h=(await recentOwner(db)).changes[0];assert.equal(h.undoable,true);await mutate(db,{op:'undo',record_id:r.id,revision:r.revision,history_id:h.id,request_id:crypto.randomUUID()});r=await openRecord(db,r.id);assert.equal(r.content.year,'2027');assert.deepEqual(r.content.notes,cleanup.expected_notes);assert.equal(r.groups[0].entries.filter(i=>!i.deleted_at).length,1404);assert.equal(r.groups[0].entries.find(i=>i.id==='legitimate').state,'pending');
 }finally{db.close();}});
test('Eau split preserves original item IDs, source groups and parent audit; all three are normal WANT inventories',async()=>{const db=fixture();try{
 const ids=db.sqlite.prepare("SELECT i.id FROM items i JOIN record_groups g ON g.id=i.group_id WHERE g.record_id=? ORDER BY i.id").all(eau.parent).map(i=>i.id);
 const result=await maintainPhase35(db,'eau-split');assert.deepEqual(result.listings.map(r=>r.count),[102,3,7]);assert.equal((await maintainPhase35(db,'eau-split')).replayed,true);
 assert.ok((await openRecord(db,eau.parent)).deleted_at);
 const after=[];for(const l of eau.listings){const r=await openRecord(db,l.id);after.push(...r.groups.flatMap(g=>g.entries.map(i=>i.id)));assert.ok(r.groups[0].entries.every(i=>i.actionable===1&&i.state==='wanted'));assert.equal(publicProjection(r).groups[0].entries.length,l.source.items.length);}
 assert.deepEqual(after.sort(),ids.sort());assert.equal(db.sqlite.prepare('SELECT count(*) n FROM provenance').get().n,3);
 }finally{db.close();}});
test('changed revisions and ambiguous source membership stop maintenance with no partial writes',async()=>{const db=fixture();try{
 db.sqlite.prepare('UPDATE records SET revision=revision+1 WHERE id=?').run(cleanup.record_id);await assert.rejects(maintainPhase35(db,'cleanup'));assert.equal(db.sqlite.prepare('SELECT count(*) n FROM items WHERE deleted_at IS NOT NULL').get().n,0);
 db.sqlite.prepare("UPDATE items SET value='Later owner correction' WHERE id='eau-group-0:0'").run();await assert.rejects(maintainPhase35(db,'eau-split'));assert.equal(db.sqlite.prepare('SELECT count(*) n FROM records').get().n,2);
 }finally{db.close();}});

test('Eau rollback restores exact opaque source states and grouping without deleting history; later owner changes block it',async()=>{const db=fixture();try{await maintainPhase35(db,'eau-split');await rollbackEauSplit(db);const parent=await openRecord(db,eau.parent);assert.equal(parent.deleted_at,null);assert.equal(parent.groups.flatMap(g=>g.entries).length,112);assert.ok(parent.groups.flatMap(g=>g.entries).every(i=>i.state===null&&i.actionable===0&&i.limitation==='Original broad interest'));for(const r of eau.listings)assert.ok((await openRecord(db,r.id)).deleted_at);}finally{db.close();}const changed=fixture();try{await maintainPhase35(changed,'eau-split');changed.sqlite.prepare('UPDATE records SET revision=2 WHERE id=?').run(eau.listings[0].id);await assert.rejects(rollbackEauSplit(changed));assert.ok((await openRecord(changed,eau.parent)).deleted_at);}finally{changed.close();}});
