import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {timingSafeEqual} from 'node:crypto';
import {localD1} from './d1-local-adapter.mjs';import {mutate,openRecord} from '../staging/records.js';import {recentOwner} from '../staging/owner.js';import * as auth from '../staging/auth.js';import worker from '../staging/worker.mjs';
Object.defineProperty(crypto.subtle,'timingSafeEqual',{value:(a,b)=>timingSafeEqual(Buffer.from(a),Buffer.from(b)),configurable:true});
function fixture(){const db=localD1();db.sqlite.exec(readFileSync(new URL('../staging/schema.sql',import.meta.url),'utf8'));db.sqlite.exec("INSERT INTO staging_import_state VALUES(1,'test','test',0,1)");return db;}
const action=(db,x)=>mutate(db,{request_id:crypto.randomUUID(),...x});
test('HAVE to WANT to HAVE is intentional replacement, preserves originals and supports safe Undo/retry',async()=>{
 const db=fixture();try{let r=await action(db,{op:'create',metadata:{set_name:'Ten cards',display_category:'OBC Wantlist'},list_type:'have_list',owned:['1','3','5','7','9']});let full=await openRecord(db,r.record_id);const gid=full.groups[0].id;
 const body={op:'replace_list',record_id:r.record_id,revision:r.revision,group_id:gid,list_type:'want_list',values:['6','8','10'],request_id:crypto.randomUUID()};r=await mutate(db,body);assert.equal((await mutate(db,body)).replayed,true);full=await openRecord(db,r.record_id);assert.deepEqual(full.groups[0].entries.filter(i=>!i.deleted_at).map(i=>i.value),['6','8','10']);assert.equal(full.groups[0].entries.filter(i=>i.deleted_at).length,5);
 let h=(await recentOwner(db)).changes[0];assert.equal(h.undoable,true);r=await action(db,{op:'undo',history_id:h.id,record_id:r.record_id,revision:r.revision});full=await openRecord(db,r.record_id);assert.equal(full.list_type,'have_list');assert.deepEqual(full.groups[0].entries.filter(i=>!i.deleted_at).map(i=>i.value),['1','3','5','7','9']);
 r=await action(db,{op:'replace_list',record_id:r.record_id,revision:r.revision,group_id:gid,list_type:'want_list',values:['6','8','10']});r=await action(db,{op:'replace_list',record_id:r.record_id,revision:r.revision,group_id:gid,list_type:'have_list',values:['2','4']});full=await openRecord(db,r.record_id);assert.deepEqual(full.groups[0].entries.filter(i=>!i.deleted_at).map(i=>[i.value,i.state]),[['2','owned'],['4','owned']]);
 await assert.rejects(action(db,{op:'edit',record_id:r.record_id,revision:r.revision,list_type:'want_list'}));
 const before=db.sqlite.prepare('SELECT count(*) n FROM items').get().n;await assert.rejects(action(db,{op:'replace_list',record_id:r.record_id,revision:1,group_id:gid,list_type:'want_list',values:['oops']}));assert.equal(db.sqlite.prepare('SELECT count(*) n FROM items').get().n,before);
 }finally{db.close();}
});
test('replacement preserves other mixed groups and opaque source entries recover through Undo',async()=>{
 const db=fixture();try{let r=await action(db,{op:'create',metadata:{set_name:'Mixed'},wanted:['Blue'],owned:['Red']});let full=await openRecord(db,r.record_id);const owned=full.groups.find(g=>g.list_type==='have_list');const oldId=owned.entries[0].id;db.sqlite.prepare('UPDATE items SET state=NULL,actionable=0,limitation=? WHERE id=?').run('Preserved named source',oldId);r=await action(db,{op:'replace_list',record_id:r.record_id,revision:r.revision,group_id:owned.id,list_type:'want_list',field_key:'items',values:['Green']});full=await openRecord(db,r.record_id);assert.equal(full.groups.find(g=>g.id!==owned.id).entries[0].value,'Blue');assert.equal(full.groups.find(g=>g.id===owned.id).entries.filter(i=>!i.deleted_at)[0].value,'Green');await assert.rejects(action(db,{op:'restore_item',record_id:r.record_id,revision:r.revision,item_id:oldId}));const h=(await recentOwner(db)).changes[0];r=await action(db,{op:'undo',history_id:h.id,record_id:r.record_id,revision:r.revision});full=await openRecord(db,r.record_id);const original=full.groups.find(g=>g.id===owned.id);assert.equal(original.list_type,'have_list');assert.equal(original.entries.find(i=>i.id===oldId).deleted_at,null);assert.equal(original.entries.find(i=>i.id===oldId).actionable,0);
 }finally{db.close();}
});
test('PIN is an explicit server-secret mode; strong-code and operator validation remain unchanged',async()=>{
 const pin=String(1000+Math.floor(Math.random()*9000)),env={OWNER_PIN:pin,OWNER_PIN_VERSION:'disposable-pin-version-0001'};assert.equal(await auth.verifyCredential(pin,env),true);assert.equal(await auth.verifyCredential('not-four-digits',env),false);assert.equal(await auth.verifyCredential(String((Number(pin)+1)%10000).padStart(4,'0'),env),false);assert.throws(()=>auth.config({...env,OWNER_PIN_VERSION:''}));
 const code=crypto.randomUUID();const strong={OWNER_AUTH_CONFIG:JSON.stringify({algorithm:'SHA-256',digest:await auth.hash(code),version:'strong-test-version-0001'})};assert.equal(await auth.verifyCredential(code,strong),true);assert.equal(await auth.verifyCredential(pin,strong),false);
});
test('PIN sessions remain revocable, expire normally, rotate only deliberately and reject public/CSRF writes',async()=>{
 const db=fixture();try{const env={DB:db,STAGING_ONLY:'true',ISOLATED_TEST_STORAGE:'true',STAGING_EDITOR:'true',OWNER_PIN:String(1000+Math.floor(Math.random()*9000)),OWNER_PIN_VERSION:'test-pin-version-0001'};const req=(path,body,headers={})=>new Request('https://staging.test'+path,{method:body?'POST':'GET',headers:{...(body?{Origin:'https://staging.test','Content-Type':'application/json'}:{}),...headers},body:body?JSON.stringify(body):undefined});
 assert.equal((await worker.fetch(req('/login',{credential:env.OWNER_PIN,remembered:true},{Origin:'https://evil.test'}),env)).status,403);
 const login=await worker.fetch(req('/login',{credential:env.OWNER_PIN,remembered:true}),env);assert.equal(login.status,200);const cookie=login.headers.get('set-cookie');assert.match(cookie,/HttpOnly/);assert.match(cookie,/Max-Age=7776000/);assert.equal((await worker.fetch(req('/action',{op:'create'}),env)).status,401);const token=cookie.split(';')[0].split('=')[1];assert.ok(await auth.validate(db,env,token));assert.equal(await auth.validate(db,{...env,OWNER_PIN_VERSION:'test-pin-version-0002'},token),null);await db.prepare('UPDATE sessions SET created_at=created_at-10,expires_at=created_at-1').run();assert.equal(await auth.validate(db,env,token),null);
 for(let i=0;i<6;i++)await worker.fetch(req('/login',{credential:'wrong',remembered:false}),env);assert.equal((await worker.fetch(req('/login',{credential:env.OWNER_PIN,remembered:false}),env)).status,429);
 }finally{db.close();}
});
test('leading-zero PINs remain strings and never accept coerced shorter numbers',async()=>{
 const pin='0'+String(Math.floor(Math.random()*1000)).padStart(3,'0');const env={OWNER_PIN:pin,OWNER_PIN_VERSION:'leading-zero-test-version-0001'};assert.equal(await auth.verifyCredential(pin,env),true);assert.equal(await auth.verifyCredential(Number(pin),env),false);assert.equal(await auth.verifyCredential(String(Number(pin)),env),false);
});
test('fixed special section meanings cannot be relabeled/replaced or duplicated by ordinary set APIs',async()=>{
 const db=fixture();try{const id='display-milwaukee-8x10-list',stamp=new Date().toISOString();db.sqlite.prepare('INSERT INTO records VALUES(?,NULL,?,?,1,?,?,NULL)').run(id,'have_list',JSON.stringify({id,set_name:'Milwaukee 8x10 List',notes:[]}),stamp,stamp);db.sqlite.prepare('INSERT INTO public_records VALUES(?,1,?,0,?)').run(id,stamp,JSON.stringify({id,list_type:'have_list',groups:[]}));
 await assert.rejects(action(db,{op:'delete',record_id:id,revision:1}));await assert.rejects(action(db,{op:'edit',record_id:id,revision:1,list_type:'uncertain',metadata:{notes:[]}}));await assert.rejects(action(db,{op:'replace_list',record_id:id,revision:1,list_type:'want_list',values:['1']}));await assert.rejects(action(db,{op:'create',metadata:{set_name:'Duplicate',display_category:'Milwaukee 8x10 List'}}));
 const r=await action(db,{op:'edit',record_id:id,revision:1,metadata:{notes:['Photos I own']},list_type:'have_list'});assert.equal(r.revision,2);
 }finally{db.close();}
});
test('opaque HAVE item removed before conversion cannot reappear as wanted; restoring group meaning makes its normal restore safe',async()=>{
 const db=fixture();try{let r=await action(db,{op:'create',metadata:{set_name:'Opaque inventory'},owned:['Named photo']});const full=await openRecord(db,r.record_id),g=full.groups[0],id=g.entries[0].id;db.sqlite.prepare('UPDATE items SET state=NULL,actionable=0,limitation=? WHERE id=?').run('Original named inventory',id);
 r=await action(db,{op:'remove_item',record_id:r.record_id,revision:r.revision,item_id:id});r=await action(db,{op:'replace_list',record_id:r.record_id,revision:r.revision,group_id:g.id,list_type:'want_list',field_key:'items',values:['Different wanted photo']});await assert.rejects(action(db,{op:'restore_item',record_id:r.record_id,revision:r.revision,item_id:id}));const h=(await recentOwner(db)).changes[0];r=await action(db,{op:'undo',history_id:h.id,record_id:r.record_id,revision:r.revision});r=await action(db,{op:'restore_item',record_id:r.record_id,revision:r.revision,item_id:id});const restored=await openRecord(db,r.record_id);assert.equal(restored.groups[0].list_type,'have_list');assert.equal(restored.groups[0].entries.find(i=>i.id===id).deleted_at,null);
 }finally{db.close();}
});
