// Read-only: consumes an operator snapshot; emits IDs/classifications, never item values or credentials.
import {readFileSync,writeFileSync} from 'node:fs';
import {editorDefaults,effectiveCategory,effectiveListType,editorPayload} from '../../owner/model.js';
const view=JSON.parse(readFileSync('foundation/staging/historical-view.json')).records;
const audit=JSON.parse(readFileSync(process.argv[2]||'foundation/.local/phase351-audit-private.json'));
const historical={category_before:[],list_type_before:[],category_after:[],list_type_after:[]};
for(const r of view){const c={...r};if(!r.id.startsWith('display-'))delete c.display_category;delete c.display_list_type;const dto={id:r.id,list_type:r.list_type,content:c};const expected={category:effectiveCategory(r),list_type:r.display_list_type||r.list_type};if((c.display_category||'OBC Wantlist')!==expected.category)historical.category_before.push(r.id);if(dto.list_type!==expected.list_type)historical.list_type_before.push(r.id);const f=editorDefaults(dto);if(f.display_category!==expected.category)historical.category_after.push(r.id);if(f.list_type!==expected.list_type)historical.list_type_after.push(r.id);if(Object.keys(editorPayload(dto,f).metadata).length)throw Error('Unrelated save changes metadata');}
const live={category_before:[],list_type_before:[],category_after:[],list_type_after:[]};
for(const row of audit.records){const content=JSON.parse(row.content_json),groups=audit.groups.filter(g=>g.record_id===row.id).map(g=>({...g,entries:audit.items.filter(i=>i.group_id===g.id)})),r={...row,content,groups};const projection=audit.public.find(p=>p.record_id===row.id);if(!projection)continue;const pub=JSON.parse(projection.public_json),expected={category:effectiveCategory(pub),list_type:effectiveListType(pub)},f=editorDefaults(r);if((content.display_category||'OBC Wantlist')!==expected.category&&expected.category)live.category_before.push(row.id);if(row.list_type!==expected.list_type)live.list_type_before.push(row.id);if(f.display_category!==expected.category&&(f.display_category||expected.category))live.category_after.push(row.id);if(f.list_type!==expected.list_type)live.list_type_after.push(row.id);}
const category_events=[],type_events=[];
for(const h of audit.history){const before=JSON.parse(h.before_json||'{}'),after=JSON.parse(h.after_json||'{}');if(h.action!=='create'&&after.metadata&&Object.hasOwn(after.metadata,'display_category')&&after.metadata.display_category!==before.metadata?.display_category)category_events.push({record_id:h.record_id,history_id:h.id,action:h.action,created_at:h.created_at,before:before.metadata?.display_category??null,after:after.metadata.display_category});if(before.list_type&&after.list_type&&before.list_type!==after.list_type)type_events.push({record_id:h.record_id,history_id:h.id,action:h.action,created_at:h.created_at,before:before.list_type,after:after.list_type});}
const result={derived_count:view.length,historical_legacy_metadata_simulation:historical,live_records: audit.records.length,live,category_events,type_events};const path='foundation/staging/phase351-audit-result.json';writeFileSync(path,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({derived_count:view.length,historical:Object.fromEntries(Object.entries(historical).map(([k,v])=>[k,v.length])),live,category_events:category_events.length,type_events:type_events.length},null,2));
