"""Generate the fixed, provenance-aware supplemental staging migration.
Only 26 bobbleheads and seven approved classifications; never full import.
Does not connect to Cloudflare or change protected/source/production files.
"""
import hashlib,json
from pathlib import Path
from foundation import storage
ROOT=Path(__file__).resolve().parents[2]
def generate():
 view=json.loads((ROOT/'foundation/staging/historical-view.json').read_text())
 originals={r['id']:r for r in storage.load_baseline()['records']}
 selected=[r for r in view['records'] if r['display_category']=='Brewers Bobblehead Wantlist' or r['id'] in view['classification_approvals']]
 samples=[]
 for display in selected:
  source=originals[display['id']];mode=display.get('display_list_type') or source['list_type']
  content={k:v for k,v in source.items() if k not in (*storage.INVENTORIES,'mixed_lists','sublists','list_type')}
  content.update(display_category=display['display_category'])
  if display.get('display_year'):content['display_year']=display['display_year']
  groups=[]
  sources=[('primary',0,source)]+[('mixed',i,g) for i,g in enumerate(source.get('mixed_lists',[]))]+[('sublist',i,g) for i,g in enumerate(source.get('sublists',[]))]
  for kind,position,g in sources:
   gid=f"{source['id']}:{kind}:{position}";keys=[k for k in storage.INVENTORIES if k in g]
   group={'id':gid,'kind':kind,'position':position,'list_type':mode if kind=='primary' else g.get('list_type',mode),'metadata':{} if kind=='primary' else {k:v for k,v in g.items() if k not in storage.INVENTORIES},'keys':keys,'entries':[]}
   for field in keys:
    state,actionable,limitation=storage.materialize(source,g,field)
    for i,value in enumerate(g[field]):group['entries'].append({'id':f'{gid}:{field}:{i}','field_key':field,'position':i,'value':value,'state':state,'actionable':actionable,'limitation':limitation,'pending_at':None,'received_at':None})
   groups.append(group)
  samples.append({'id':source['id'],'list_type':mode,'content':content,'groups':groups,'source':source,'source_sha256':hashlib.sha256(storage.dumps(source).encode()).hexdigest()})
 assert len(samples)==33
 path=ROOT/'foundation/staging/phase34-samples.js'
 path.write_text('// Generated by python -m foundation.staging.phase34_migration; protected sources unchanged.\nexport const samples='+json.dumps(samples,ensure_ascii=False,separators=(',',':'))+';\nexport const selectionSha256='+json.dumps(hashlib.sha256(storage.dumps(samples).encode()).hexdigest())+';\n')
 return samples
if __name__=='__main__':generate();print('33 fixed historical samples prepared; no remote writes')
