import {test,expect} from '@playwright/test';import AxeBuilder from '@axe-core/playwright';import {mkdirSync} from 'node:fs';
const origin='https://isolated.wantlist.test';
const evidence='docs/evidence/phase3b4';mkdirSync(evidence,{recursive:true});
test.beforeEach(async({page})=>{
 await fetch('http://127.0.0.1:5181/reset',{method:'POST'});
 await page.route(origin+'/**',async route=>{
  const req=route.request();const response=await fetch('http://127.0.0.1:5181/relay',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:new URL(req.url()).pathname+new URL(req.url()).search,method:req.method(),headers:await req.allHeaders(),body:req.postData()})});
  const r=await response.json();await route.fulfill({status:r.status,headers:r.headers,body:Buffer.from(r.body,'base64')});
 });await page.goto(origin);await expect(page.locator('.listing-row').first()).toBeVisible();
});
const dialog=page=>page.getByRole('dialog');
const item=(page,value)=>dialog(page).locator('.owner-item').filter({has:page.locator('strong').filter({hasText:new RegExp('^'+value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'$')})});
async function login(page){await page.getByRole('button',{name:'Owner Login',exact:true}).click();await page.getByLabel('Owner PIN',{exact:true}).fill('4826');await dialog(page).getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('button',{name:'Log out'})).toBeVisible();}
async function create(page,mode='want_list',category='OBC Wantlist'){
 await page.getByRole('button',{name:'Add a new set'}).click();const d=dialog(page);await d.getByLabel('Year or years').fill('1995(?)');await d.getByLabel('Manufacturer',{exact:true}).fill('Topps');await d.getByLabel('Set name',{exact:true}).fill('Twilight actor cards');await d.getByRole('combobox',{name:'Category',exact:true}).selectOption(category);await d.getByRole('combobox',{name:'List type',exact:true}).selectOption(mode);if(mode==='complete')await d.getByRole('checkbox').check();await d.getByRole('button',{name:'Create set'}).click();await expect(d.getByRole('button',{name:'Save changes'})).toBeVisible();
}
async function add(page,text,names=false){const d=dialog(page);if(names)await d.getByLabel('What are you entering?').selectOption('names');await d.getByLabel(names?'One name or item on each line':'Card numbers or codes').fill(text);await d.getByRole('button',{name:'Add cards',exact:true}).click();await expect(item(page,names?text.split('\n')[0]:text.split(/[\s,]+/)[0])).toBeVisible();}
async function axe(page){expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
async function shot(page,info,label){
 if(label==='unified-editor')await dialog(page).evaluate(d=>{d.scrollTop=0;});
 if(label==='individual-editing')await dialog(page).locator('.owner-group').first().scrollIntoViewIfNeeded();
 if(label==='bulk-edit')await dialog(page).locator('.bulk-editor').evaluate(el=>{const d=el.closest('dialog');d.scrollTop+=el.getBoundingClientRect().top-d.getBoundingClientRect().top-20;});
 await page.screenshot({path:`${evidence}/${info.project.name}-${label}.png`});}
test('unified editor, individual states, natural order, Bulk Edit, pending safeguard and Undo',async({page,context},info)=>{
 await login(page);await create(page);await add(page,'10 KB-12 2 KB-2 1');
 const d=dialog(page);await expect(d.getByRole('button',{name:'Edit set information'})).toHaveCount(0);await expect(d.getByLabel('These are')).toHaveCount(0);await expect(d.getByText('More',{exact:true})).toHaveCount(0);
 expect(await d.locator('.owner-item strong').allTextContents()).toEqual(['1','2','10','KB-2','KB-12']);await d.getByRole('textbox',{name:'Notes',exact:true}).fill('Unsaved notes survive item edits');await item(page,'2').getByRole('button',{name:'Mark Pending'}).click();await expect(item(page,'2')).toContainText('Someone is sending this');await expect(item(page,'2').getByRole('button',{name:'Cancel Pending'})).toBeVisible();
 await expect(d.getByRole('textbox',{name:'Notes',exact:true})).toHaveValue('Unsaved notes survive item edits');await shot(page,info,'individual-editing');await axe(page);await d.getByRole('textbox',{name:'Notes',exact:true}).fill('Owner notes kept');await d.getByRole('button',{name:'Save changes'}).click();await expect(d.getByRole('textbox',{name:'Notes',exact:true})).toHaveValue('Owner notes kept');await shot(page,info,'unified-editor');
 await d.getByRole('button',{name:'Bulk Edit',exact:true}).click();await expect(d.getByLabel('Current cards/items')).toHaveValue('10 KB-12 2 KB-2 1');await d.getByLabel('Current cards/items').fill('2 3 10');await expect(d.locator('.bulk-editor [role=status]')).toContainText('1 added');await d.getByRole('checkbox',{name:/I confirm these identifiers/}).check();await shot(page,info,'bulk-edit');await axe(page);await d.getByRole('button',{name:'Apply changes'}).click();await expect(d.getByLabel('Current cards/items')).toHaveCount(0);await expect(item(page,'2')).toContainText('Someone is sending this');expect(await d.locator('.owner-item strong').allTextContents()).toEqual(['2','3','10']);
 await d.getByRole('button',{name:'Bulk Edit',exact:true}).click();await d.getByLabel('Current cards/items').fill('3');await expect(d.getByText(/Warning: 1 pending entries/)).toBeVisible();await d.getByRole('button',{name:'Cancel',exact:true}).click();await expect(item(page,'2')).toBeVisible();
 await item(page,'2').getByRole('button',{name:'Mark Received'}).click();await expect(item(page,'2')).toContainText('Already owned');await expect(item(page,'2').getByRole('button',{name:'Mark Pending'})).toHaveCount(0);await expect(item(page,'2').getByText('Correct a mistake')).toHaveCount(0);
 await d.getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('button',{name:'Recent Changes'}).click();await d.locator('.recent-list li').first().getByRole('button',{name:'Undo',exact:true}).click();await d.locator('.recent-list li').first().getByRole('button',{name:'Open set'}).click();await expect(item(page,'2')).toContainText('Someone is sending this');
 const cookie=(await context.cookies(origin)).find(c=>c.name==='__Host-wantlist_owner');expect(cookie.httpOnly&&cookie.secure).toBe(true);expect(cookie.sameSite).toBe('Strict');
});
test('explicit HAVE/WANT conversion, COMPLETE recovery, multiword names and persistence',async({page},info)=>{
 await login(page);await create(page,'have_list');await add(page,'1 3 5 7 9');const d=dialog(page);await expect(item(page,'1').getByRole('button',{name:'Mark Received'})).toHaveCount(0);
 await d.getByRole('combobox',{name:'List type',exact:true}).selectOption('want_list');await d.getByRole('button',{name:'Save changes'}).click();await expect(d.getByLabel('Current cards/items')).toHaveValue('');await d.getByLabel('Current cards/items').fill('6 8 10');await d.getByRole('checkbox',{name:/I confirm these identifiers/}).check();await d.getByRole('button',{name:'Apply changes'}).click();await expect(item(page,'6')).toContainText('Still needed');await expect(item(page,'1')).toHaveCount(0);
 await add(page,'Rod Serling\nWilliam Shatner',true);await d.getByRole('combobox',{name:'List type',exact:true}).selectOption('complete');await d.getByRole('checkbox',{name:/I confirm this set is COMPLETE/}).check();await d.getByRole('button',{name:'Save changes'}).click();await expect(d.getByRole('button',{name:'Add cards',exact:true})).toBeDisabled();await expect(d.getByRole('button',{name:'Mark Received'})).toHaveCount(0);
 await d.getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('button',{name:'Recent Changes'}).click();await d.locator('.recent-list li').first().getByRole('button',{name:'Undo',exact:true}).click();await d.locator('.recent-list li').first().getByRole('button',{name:'Open set'}).click();await expect(item(page,'Rod Serling')).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'Log out'})).toBeVisible();await page.getByLabel('Search this category').fill('Twilight actor cards');await page.locator('.listing-row summary').first().click();await expect(page.locator('.listing-content')).toContainText('Rod Serling');await axe(page);
});
test('owner categories create, rename, move, protect nonempty and historical categories',async({page},info)=>{
 await login(page);await page.getByRole('button',{name:'Manage categories'}).click();const d=dialog(page);await d.getByLabel('New category name').fill('Twilight Zone Actor Wantlist');await shot(page,info,'new-category');await d.getByRole('button',{name:'Create category'}).click();await expect(d.getByLabel('Rename Twilight Zone Actor Wantlist')).toBeVisible();await d.getByRole('button',{name:'Close',exact:true}).click();await create(page,'want_list','Twilight Zone Actor Wantlist');await add(page,'Rod Serling',true);await d.getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('button',{name:'Manage categories'}).click();await d.getByRole('button',{name:'Remove empty category'}).click();await expect(d.getByRole('alert')).toContainText('may contain listings');await d.getByLabel('Rename Twilight Zone Actor Wantlist').fill('Twilight Actors');await d.getByRole('button',{name:'Rename category'}).click();await expect(d.getByLabel('Rename Twilight Actors')).toBeVisible();await d.getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('combobox',{name:'Category',exact:true}).selectOption('Twilight Actors');await expect(page.locator('.listing-row')).toHaveCount(1);await page.locator('.listing-row summary').click();await page.getByRole('button',{name:'Edit this set'}).click();await d.getByRole('combobox',{name:'Category',exact:true}).selectOption('OBC Wantlist');await d.getByRole('button',{name:'Save changes'}).click();await d.getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('button',{name:'Manage categories'}).click();await d.getByRole('button',{name:'Remove empty category'}).click();await expect(d.getByLabel('Rename Twilight Actors')).toHaveCount(0);await axe(page);
});
test('filters, 26 bobbleheads, year uncertainty, compact read-only browsing and authentication boundaries',async({page},info)=>{
 await page.getByRole('combobox',{name:'Category',exact:true}).selectOption('Brewers Bobblehead Wantlist');await expect(page.locator('.listing-row')).toHaveCount(26);await page.getByRole('combobox',{name:'Category',exact:true}).selectOption('UV Wantlist');await page.getByRole('combobox',{name:'Year',exact:true}).selectOption('2007');await page.getByRole('combobox',{name:'Manufacturer',exact:true}).selectOption('Upper Deck');await page.getByLabel('Search this category').fill('Upper Deck');await expect(page.locator('.listing-row')).toHaveCount(1);await shot(page,info,'filters');await axe(page);
 await expect(page.getByRole('button',{name:'Edit this set'})).toHaveCount(0);
 const result=await page.evaluate(async()=>{
  const post=(path,body,headers={})=>fetch(path,{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)}).then(r=>r.status);
  return {publicWrite:await post('/action',{op:'create',request_id:crypto.randomUUID()}),publicCategory:await post('/owner/category',{op:'create',name:'Forbidden',request_id:crypto.randomUUID()}),diagnostic:await post('/test/batch',{statements:[]})};
 });expect(result).toEqual({publicWrite:401,publicCategory:401,diagnostic:403});
 await page.getByRole('combobox',{name:'Year',exact:true}).selectOption('1990');await page.getByRole('combobox',{name:'Manufacturer',exact:true}).selectOption('');await page.getByLabel('Search this category').fill('');await expect(page.locator('.year-note').first()).toContainText('Year uncertain');
});

test('lost save response retries idempotently; expired sessions require fresh owner verification',async({page})=>{
 await login(page);await create(page);let lost=false;const ids=[];
 await page.route(origin+'/action',async route=>{
  const req=route.request();ids.push(req.postDataJSON().request_id);
  const response=await fetch('http://127.0.0.1:5181/relay',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:'/action',method:'POST',headers:await req.allHeaders(),body:req.postData()})});const r=await response.json();
  if(!lost&&r.status===200){lost=true;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Simulated lost response after local commit'})});}
  else await route.fulfill({status:r.status,headers:r.headers,body:Buffer.from(r.body,'base64')});
 });
 const d=dialog(page);await d.getByLabel('Card numbers or codes').fill('47');await d.getByRole('button',{name:'Add cards',exact:true}).click();await expect(d.getByRole('button',{name:'Try saving again'})).toBeVisible();await expect(d.getByRole('button',{name:'Add cards',exact:true})).toBeDisabled();await d.getByRole('button',{name:'Try saving again'}).click();await expect(item(page,'47')).toHaveCount(1);expect(ids[0]).toBe(ids[1]);
 await fetch('http://127.0.0.1:5181/expire',{method:'POST'});await item(page,'47').getByRole('button',{name:'Mark Received'}).click();await expect(d.getByRole('heading',{name:'Owner Login'})).toBeVisible();await expect(d.getByRole('alert')).toContainText('verified again');await page.getByLabel('Owner PIN',{exact:true}).fill('4826');await d.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('button',{name:'Log out'})).toBeVisible();await page.getByRole('button',{name:'Log out'}).click();await expect(page.getByRole('button',{name:'Owner Login'})).toBeVisible();
});
