import {test,expect} from '@playwright/test';import AxeBuilder from '@axe-core/playwright';import {mkdirSync} from 'node:fs';
const origin='https://isolated.wantlist.test',evidence='docs/evidence/phase3b5';mkdirSync(evidence,{recursive:true});
test.beforeEach(async({page})=>{await fetch('http://127.0.0.1:5181/reset',{method:'POST'});await page.route(origin+'/**',async route=>{const req=route.request();const r=await (await fetch('http://127.0.0.1:5181/relay',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:new URL(req.url()).pathname+new URL(req.url()).search,method:req.method(),headers:await req.allHeaders(),body:req.postData()})})).json();await route.fulfill({status:r.status,headers:r.headers,body:Buffer.from(r.body,'base64')});});await page.goto(origin);await expect(page.locator('.listing-row').first()).toBeVisible();});
const d=page=>page.getByRole('dialog');
const item=(page,value)=>d(page).locator('.owner-item').filter({has:page.locator('strong').filter({hasText:new RegExp('^'+value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'$')})});
async function login(page){await page.getByRole('button',{name:'Owner Login',exact:true}).click();await page.getByLabel('Owner PIN',{exact:true}).fill('4826');await d(page).getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('button',{name:'Log out'})).toBeVisible();}
async function create(page,mode='want_list',category='OBC Wantlist'){await page.getByRole('button',{name:'Add a new set'}).click();await d(page).getByLabel('Year or years').fill('1995(?)');await d(page).getByLabel('Manufacturer',{exact:true}).fill('Topps');await d(page).getByLabel('Set name',{exact:true}).fill('Twilight actor cards');await d(page).getByRole('combobox',{name:'Category',exact:true}).selectOption(category);await d(page).getByRole('combobox',{name:'List type',exact:true}).selectOption(mode);await d(page).getByRole('button',{name:'Create set'}).click();await expect(d(page).getByRole('button',{name:'Save changes'})).toBeDisabled();}
async function add(page,text,names=false){if(names)await d(page).getByRole('combobox',{name:'Entry format',exact:true}).selectOption('names');await d(page).getByLabel(names?'One name or item on each line':'Card numbers or codes').fill(text);await d(page).getByRole('button',{name:'Add to draft'}).click();}
async function save(page){await d(page).getByRole('button',{name:'Save changes',exact:true}).click();await expect(d(page).getByRole('button',{name:'Save changes',exact:true})).toBeDisabled().catch(async e=>{console.log('SAVE ERROR',await d(page).getByRole('alert').allTextContents());throw e;});await expect(d(page).getByText('Changes saved',{exact:true})).toBeVisible();}
async function axe(page){expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(await d(page).count()?await d(page).evaluate(el=>el.scrollWidth<=el.clientWidth):true).toBe(true);}
async function shot(page,info,label){await page.screenshot({path:`${evidence}/${info.project.name}-${label}.png`});}
async function filter(page,label,text){const box=page.getByRole('combobox',{name:label,exact:true});await box.click();await box.fill(text);await page.getByRole('option',{name:text,exact:true}).click();}
async function openCategory(page,category,index=0){await page.getByRole('combobox',{name:'Category',exact:true}).selectOption(category);await page.locator('.listing-row summary').nth(index).click();await page.getByRole('button',{name:'Edit this set'}).nth(0).click();}
test('draft editing, only Pending/Remove, sticky controls, discard protection, Bulk Edit and Undo',async({page,context},info)=>{
 await login(page);await create(page);await add(page,'10 KB-12 2 KB-2 1');const dialog=d(page);
 expect(await dialog.locator('.owner-item strong').allTextContents()).toEqual(['1','2','10','KB-2','KB-12']);await expect(dialog.getByRole('button',{name:'Mark Received'})).toHaveCount(0);
 await dialog.getByRole('textbox',{name:'Notes',exact:true}).fill('Owner notes');await item(page,'2').getByRole('button',{name:'Mark Pending'}).click();await expect(item(page,'2').getByRole('button',{name:'Cancel Pending'})).toBeVisible();
 await dialog.locator('.owner-group').scrollIntoViewIfNeeded();await shot(page,info,'simplified-actions');await axe(page);
 await dialog.getByRole('button',{name:'Close',exact:true}).click();await expect(dialog.getByRole('alertdialog')).toContainText('You have unsaved changes. Are you sure you want to discard them?');await dialog.getByRole('button',{name:'Keep editing'}).click();await expect(dialog.getByRole('textbox',{name:'Notes',exact:true})).toHaveValue('Owner notes');await save(page);
 await dialog.getByRole('button',{name:'Bulk Edit',exact:true}).click();await dialog.getByLabel('Current cards/items').fill('2 3 10');await dialog.getByRole('checkbox',{name:/I confirm these identifiers/}).check();await shot(page,info,'bulk-edit');await dialog.getByRole('button',{name:'Apply changes'}).click();await expect(item(page,'2').getByRole('button',{name:'Cancel Pending'})).toBeVisible();await expect(dialog.getByRole('button',{name:'Save changes'})).toBeEnabled();await save(page);
 await dialog.getByRole('button',{name:'Bulk Edit',exact:true}).click();await dialog.getByLabel('Current cards/items').fill('3');await expect(dialog.getByText(/Warning: 1 pending/)).toBeVisible();await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await expect(dialog.getByRole('button',{name:'Save changes'})).toBeDisabled();
 await dialog.evaluate(el=>el.scrollTop=0);await shot(page,info,'unified-editor');await dialog.getByRole('button',{name:'Close',exact:true}).click();await page.getByLabel('Search this category').fill('Twilight');await page.locator('.listing-row summary').click();await expect(page.locator('.listing-content')).toContainText('Pending: 2');await expect(page.locator('.listing-content')).not.toContainText('duplicates');await shot(page,info,'public-pending');await axe(page);
 await page.getByRole('button',{name:'Edit this set'}).click();await item(page,'2').getByRole('button',{name:'Cancel Pending'}).click();await save(page);await d(page).getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('button',{name:'Recent Changes'}).click();await d(page).locator('.recent-list li').first().getByRole('button',{name:'Undo',exact:true}).click();await d(page).locator('.recent-list li').first().getByRole('button',{name:'Open set'}).click();await expect(item(page,'2').getByRole('button',{name:'Cancel Pending'})).toBeVisible();
 await d(page).getByRole('textbox',{name:'Notes',exact:true}).fill('Discard me');await d(page).getByRole('button',{name:'Close',exact:true}).click();await d(page).getByRole('button',{name:'Discard changes'}).click();await page.getByRole('button',{name:'Edit this set'}).click();await expect(d(page).getByRole('textbox',{name:'Notes',exact:true})).toHaveValue('Owner notes');
 const cookie=(await context.cookies(origin)).find(c=>c.name==='__Host-wantlist_owner');expect(cookie.httpOnly&&cookie.secure).toBe(true);expect(cookie.sameSite).toBe('Strict');
});
test('explicit conversion, COMPLETE history, natural/original public order and reload',async({page})=>{
 await login(page);await create(page,'have_list');await add(page,'1 3 5 7 9');await save(page);await d(page).getByRole('combobox',{name:'List type',exact:true}).selectOption('want_list');await expect(d(page).getByLabel('Current cards/items')).toHaveValue('');await d(page).getByLabel('Current cards/items').fill('6 8 10');await d(page).getByRole('checkbox',{name:/I confirm these identifiers/}).check();await d(page).getByRole('button',{name:'Apply changes'}).click();await save(page);await expect(item(page,'1')).toHaveCount(0);
 await add(page,'Rod Serling\nWilliam Shatner',true);await d(page).getByRole('combobox',{name:'Entry order',exact:true}).selectOption('original');await save(page);expect(await d(page).locator('.owner-item strong').allTextContents()).toEqual(['6','8','10','Rod Serling','William Shatner']);await d(page).getByRole('button',{name:'Close',exact:true}).click();await page.reload();await page.getByLabel('Search this category').fill('Twilight');await page.locator('.listing-row summary').click();await expect(page.locator('.listing-content')).toContainText('6, 8, 10, Rod Serling, William Shatner');await page.getByRole('button',{name:'Edit this set'}).click();await expect(d(page).getByRole('combobox',{name:'Entry order',exact:true})).toHaveValue('original');await d(page).getByRole('combobox',{name:'List type',exact:true}).selectOption('complete');await d(page).getByRole('checkbox',{name:/I confirm this set is COMPLETE/}).check();await save(page);await expect(d(page).getByRole('button',{name:'Add to draft'})).toBeDisabled();await axe(page);
});
test('special collections share complete inventories, three Eau listings, Bobbleheads and long-list sticky controls',async({page},info)=>{
 await login(page);await openCategory(page,'Milwaukee 8x10 List');await expect(d(page).locator('.owner-group')).toHaveCount(1);await add(page,'Megill, T',true);await d(page).getByRole('searchbox',{name:'Search within listing',exact:true}).fill('Megill');await expect(item(page,'Megill, T')).toBeVisible();await save(page);await d(page).getByRole('button',{name:'Bulk Edit',exact:true}).click();expect(await d(page).getByLabel('Current cards/items').inputValue()).toContain('Aaron, H');expect(await d(page).getByLabel('Current cards/items').inputValue()).toContain('Megill, T');await d(page).getByRole('button',{name:'Cancel',exact:true}).click();await d(page).getByRole('button',{name:'Close',exact:true}).click();await expect(page.locator('.listing-content')).toContainText('Megill, T');await expect(page.locator('.listing-content')).not.toContainText('Preserved Source Information');
 await page.getByRole('combobox',{name:'Category',exact:true}).selectOption('Eau Claire Players');await expect(page.locator('.listing-row')).toHaveCount(3);await page.locator('.listing-row summary').filter({hasText:'Major League Players'}).click();await page.getByRole('button',{name:'Edit this set'}).click();await add(page,'New practice player',true);await save(page);await d(page).getByRole('searchbox',{name:'Search within listing',exact:true}).fill('New practice player');await item(page,'New practice player').getByRole('button',{name:'Mark Pending'}).click();await save(page);await expect(item(page,'New practice player').getByRole('button',{name:'Cancel Pending'})).toBeVisible();await d(page).getByRole('button',{name:'Close',exact:true}).click();await expect(page.locator('.listing-content')).toContainText('Pending: New practice player');
 await openCategory(page,'Brewers Bobblehead Wantlist');await add(page,'Practice event item',true);await save(page);await d(page).getByRole('button',{name:'Close',exact:true}).click();await expect(page.locator('.listing-content')).toContainText('Practice event item');
 await openCategory(page,'UV Wantlist');await d(page).getByRole('button',{name:'Show all entries'}).click();await d(page).evaluate(el=>el.scrollTop=el.scrollHeight);await expect(d(page).getByRole('button',{name:'Close',exact:true})).toBeInViewport();await expect(d(page).getByRole('button',{name:'Save changes'})).toBeInViewport();await shot(page,info,'sticky-controls');await axe(page);
});
test('searchable filters support keyboard and reset, branding and public/auth boundaries',async({page},info)=>{
 await expect(page.getByRole('heading',{name:"Jason's Want List",exact:true})).toBeVisible();await expect(page.getByText('Jason Christopherson',{exact:true})).toBeVisible();await expect(page).toHaveTitle(/Jason's Want List/);await page.getByRole('combobox',{name:'Category',exact:true}).selectOption('UV Wantlist');await page.getByRole('combobox',{name:'Year',exact:true}).click();await page.getByRole('combobox',{name:'Year',exact:true}).fill('1951');await expect(page.getByRole('option',{name:'1951',exact:true})).toBeVisible();await shot(page,info,'searchable-year');await page.getByRole('combobox',{name:'Year',exact:true}).press('Escape');await filter(page,'Year','2007');const manufacturer=page.getByRole('combobox',{name:'Manufacturer',exact:true});await manufacturer.click();await manufacturer.fill('upper');await manufacturer.press('Enter');await page.getByLabel('Search this category').fill('Upper Deck');await expect(page.locator('.listing-row')).toHaveCount(1);await shot(page,info,'branding-filters');await manufacturer.click();await manufacturer.fill('Top');await expect(page.getByRole('option',{name:'Topps',exact:true})).toBeVisible();await shot(page,info,'searchable-manufacturer');await manufacturer.press('Escape');await page.getByRole('button',{name:'Clear Manufacturer'}).click();await page.getByRole('button',{name:'Clear Year'}).click();await filter(page,'Year','1990');await page.getByLabel('Search this category').fill('');await expect(page.locator('.year-note').first()).toContainText('Year uncertain');await axe(page);
 const result=await page.evaluate(async()=>{const post=(path,body)=>fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}).then(r=>r.status);return [await post('/action',{op:'edit_session',request_id:crypto.randomUUID()}),await post('/owner/category',{op:'create',name:'Forbidden',request_id:crypto.randomUUID()}),await post('/test/batch',{statements:[]})];});expect(result).toEqual([401,401,403]);await expect(page.getByRole('button',{name:'Edit this set'})).toHaveCount(0);
});
test('categories create/rename/move and protect occupied defaults',async({page},info)=>{
 await login(page);await page.getByRole('button',{name:'Manage categories'}).click();await d(page).getByLabel('New category name').fill('Twilight Zone Actor Wantlist');await shot(page,info,'new-category');await d(page).getByRole('button',{name:'Create category'}).click();await expect(d(page).getByLabel('Rename Twilight Zone Actor Wantlist')).toBeVisible();await d(page).getByRole('button',{name:'Close',exact:true}).click();await create(page,'want_list','Twilight Zone Actor Wantlist');await add(page,'Rod Serling',true);await save(page);await d(page).getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('button',{name:'Manage categories'}).click();await d(page).getByRole('button',{name:'Remove empty category'}).click();await expect(d(page).getByRole('alert')).toContainText('may contain listings');await d(page).getByLabel('Rename Twilight Zone Actor Wantlist').fill('Twilight Actors');await d(page).getByRole('button',{name:'Rename category'}).click();await expect(d(page).getByLabel('Rename Twilight Actors')).toBeVisible();await d(page).getByRole('button',{name:'Close',exact:true}).click();await openCategory(page,'Twilight Actors');await d(page).getByRole('combobox',{name:'Category',exact:true}).selectOption('OBC Wantlist');await save(page);await d(page).getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('button',{name:'Manage categories'}).click();await d(page).getByRole('button',{name:'Remove empty category'}).click();await expect(d(page).getByLabel('Rename Twilight Actors')).toHaveCount(0);await axe(page);
});
test('lost response retries same receipt; expiry preserves draft and reauthentication saves it',async({page})=>{
 await login(page);await create(page);await add(page,'47');let lost=false;const ids=[];await page.route(origin+'/action',async route=>{const req=route.request();ids.push(req.postDataJSON().request_id);const r=await (await fetch('http://127.0.0.1:5181/relay',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:'/action',method:'POST',headers:await req.allHeaders(),body:req.postData()})})).json();if(!lost&&r.status===200){lost=true;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Simulated lost response'})});}else await route.fulfill({status:r.status,headers:r.headers,body:Buffer.from(r.body,'base64')});});await d(page).getByRole('button',{name:'Save changes'}).click();await expect(d(page).getByRole('button',{name:'Try saving again'})).toBeVisible();await d(page).getByRole('button',{name:'Try saving again'}).click();await expect(item(page,'47')).toHaveCount(1);await expect(d(page).getByRole('button',{name:'Try saving again'})).toHaveCount(0);await expect(d(page).getByRole('button',{name:'Save changes'})).toBeDisabled();expect(ids[0]).toBe(ids[1]);await fetch('http://127.0.0.1:5181/expire',{method:'POST'});await d(page).getByRole('textbox',{name:'Notes',exact:true}).fill('Preserved expired draft');await item(page,'47').getByRole('button',{name:'Mark Pending'}).click();await d(page).getByRole('button',{name:'Save changes'}).click();await expect(d(page).getByRole('alert')).toContainText('verified again');await page.getByLabel('Owner PIN',{exact:true}).fill('4826');await d(page).getByRole('button',{name:'Sign in',exact:true}).click();await expect(d(page).getByRole('textbox',{name:'Notes',exact:true})).toHaveValue('Preserved expired draft');await save(page);await expect(item(page,'47').getByRole('button',{name:'Cancel Pending'})).toBeVisible();
});
test('concurrent edits reject stale Save and preserve the local draft until explicit discard',async({page})=>{
 await login(page);await create(page);await add(page,'2');await save(page);await d(page).getByRole('textbox',{name:'Notes',exact:true}).fill('My unsaved note');const id=await page.evaluate(async()=>{const page=await (await fetch('/public/page')).json();return page.records.find(r=>r.set_name==='Twilight actor cards').id;});await fetch('http://127.0.0.1:5181/external-edit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});await d(page).getByRole('button',{name:'Save changes'}).click();await expect(d(page).getByRole('alert')).toContainText('changed since you opened');await expect(d(page).getByRole('textbox',{name:'Notes',exact:true})).toHaveValue('My unsaved note');await d(page).getByRole('button',{name:'Close',exact:true}).click();await d(page).getByRole('button',{name:'Discard changes'}).click();await page.getByLabel('Search this category').fill('Twilight');await page.locator('.listing-row summary').click();await page.getByRole('button',{name:'Edit this set'}).click();await expect(d(page).getByRole('textbox',{name:'Notes',exact:true})).toHaveValue('Other device edit');
});
